# Generated by Django 6.0.1 on 2026-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="ATJ", max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image de fond de la page d'accueil",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Révélez votre Potentiel", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Configuration Site",
                "verbose_name_plural": "Configuration Site",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        help_text="Ex: Directrice Académique, Mentor Python...",
                        max_length=100,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                (
                    "ordre",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
    ]
