# Generated by Django 6.0.1 on 2026-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_description",
            field=models.TextField(
                blank=True, help_text="Texte principal de la page À propos"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title",
            field=models.CharField(default="À Propos de Nous", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text",
            field=models.TextField(blank=True, help_text="Texte court en bas de page"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.TextField(
                blank=True, default="La plateforme d'excellence pour votre carrière."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_text",
            field=models.TextField(
                blank=True,
                default="Nous formons la prochaine génération de leaders.",
                help_text="Texte affiché dans la section Mission",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_title",
            field=models.CharField(default="Notre Mission", max_length=200),
        ),
    ]
