# Generated by Django 6.0.1 on 2026-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="adresse",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
