# Generated by Django 6.0.1 on 2026-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("lieu", models.CharField(max_length=200)),
                ("lien_inscription", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
