# Generated by Django 6.0.7 on 2026-08-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('categorie', models.CharField(choices=[('art_oratoire', 'Art Oratoire'), ('leadership', 'Leadership'), ('informatique', 'Informatique'), ('langues', 'Langues'), ('affaires', 'Affaires')], default='art_oratoire', max_length=20)),
                ('description', models.TextField(verbose_name='Description')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='formations/', verbose_name='Image de couverture')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix (0 = gratuit)')),
                ('conditions', models.TextField(blank=True, verbose_name='Pré-requis / Conditions')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publier sur le site')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['categorie', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la leçon')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('video', models.FileField(blank=True, help_text='Uploader un fichier vidéo (prioritaire sur le lien)', null=True, upload_to='videos/', verbose_name='Vidéo (MP4)')),
                ('video_url', models.URLField(blank=True, help_text='Lien vidéo externe (utilisé si aucun fichier uploadé)', null=True, verbose_name='Ou lien YouTube/Vimeo')),
                ('contenu_texte', models.TextField(blank=True, help_text='Texte, HTML ou description de la leçon', verbose_name='Contenu texte')),
                ('ressource_fichier', models.FileField(blank=True, help_text="Support téléchargeable pour l'étudiant", null=True, upload_to='ressources/', verbose_name='Document (PDF, ZIP)')),
                ('duree_minutes', models.IntegerField(default=10, verbose_name='Durée (minutes)')),
                ('est_gratuit', models.BooleanField(default=False, help_text='Accessible sans paiement ni inscription', verbose_name='Accès gratuit (teaser)')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formations.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_paiement', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé')], default='pending', max_length=20)),
                ('statut_validation', models.BooleanField(default=False, verbose_name='Validée')),
                ('progression', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('completed_lessons', models.ManyToManyField(blank=True, related_name='completed_by', to='formations.lecon', verbose_name='Leçons complétées')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='formations.inscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_session', models.CharField(choices=[('en_ligne', '🌐 En Ligne'), ('presentiel', '📍 Présentiel')], default='en_ligne', max_length=15, verbose_name='Type')),
                ('nom', models.CharField(default='Accès Libre', help_text="Ex: 'Promo Octobre 2026' ou 'Accès Libre'", max_length=200, verbose_name='Nom de la session')),
                ('date_debut', models.DateField(blank=True, help_text='Obligatoire si Présentiel', null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, default='Siège ATJ', help_text='Pour le présentiel', max_length=200, verbose_name='Lieu')),
                ('places_disponibles', models.IntegerField(default=20, verbose_name='Places disponibles')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.session', verbose_name='Session'),
        ),
    ]
