# Generated by Django 6.0.1 on 2026-01-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="progression",
            field=models.IntegerField(
                default=0, help_text="Pourcentage de progression (0-100)"
            ),
        ),
    ]
