# Generated by Django 6.0.1 on 2026-01-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0003_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("art_oratoire", "Art Oratoire"),
                    ("leadership", "Leadership"),
                    ("informatique", "Informatique"),
                    ("langues", "Langues"),
                    ("affaires", "Affaires"),
                ],
                default="art_oratoire",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="est_publie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programme",
            name="prix",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="programme",
            name="type_formation",
            field=models.CharField(
                choices=[
                    ("online", "En Ligne"),
                    ("offline", "Présentiel"),
                    ("hybrid", "Hybride"),
                ],
                default="offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="est_permanente",
            field=models.BooleanField(
                default=False,
                help_text="Pour les cours en ligne accessibles tout le temps",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="lieu",
            field=models.CharField(blank=True, default="Siège ATJ", max_length=200),
        ),
        migrations.AlterField(
            model_name="session",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Chapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres",
                        to="formations.programme",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Lecon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "contenu",
                    models.TextField(help_text="Contenu HTML, Texte ou Embed Vidéo"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Lien YouTube/Vimeo", null=True
                    ),
                ),
                ("duree_minutes", models.IntegerField(default=10)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "est_gratuit",
                    models.BooleanField(
                        default=False, help_text="Accessible sans paiement (teaser)"
                    ),
                ),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecons",
                        to="formations.chapitre",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
    ]
