# Generated by Django 6.0.1 on 2026-01-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0004_programme_categorie_programme_est_publie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("fichier", models.FileField(upload_to="ressources_cours/")),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "lecon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ressources",
                        to="formations.lecon",
                    ),
                ),
            ],
        ),
    ]
