# Generated by Django 6.0.1 on 2026-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0005_ressource"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecon",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Vidéo locale (MP4, WebM). Prioritaire sur le lien URL.",
                null=True,
                upload_to="cours_videos/",
            ),
        ),
    ]
