# Generated by Django 6.0.1 on 2026-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0006_lecon_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapitre",
            name="pdf_resume",
            field=models.FileField(
                blank=True,
                help_text="Résumé PDF du chapitre (téléchargeable)",
                null=True,
                upload_to="chapitres_resumes/",
            ),
        ),
    ]
