# Generated by Django 6.0.1 on 2026-01-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0007_chapitre_pdf_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="conditions",
            field=models.TextField(
                blank=True,
                help_text="Pré-requis, diplômes nécessaires ou matériel requis.",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="date_limite_inscription",
            field=models.DateField(
                blank=True,
                help_text="Date limite pour accepter de nouvelles inscriptions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="est_publie",
            field=models.BooleanField(
                default=False, verbose_name="Publier sur le site"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Frais d'inscription",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="est_permanente",
            field=models.BooleanField(
                default=False,
                help_text="Cocher pour les formations en ligne accessibles à tout moment",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="lieu",
            field=models.CharField(
                blank=True,
                default="Siège ATJ",
                help_text="Pour le présentiel",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="places_disponibles",
            field=models.IntegerField(default=20, verbose_name="Place limites"),
        ),
    ]
