# Generated by Django 6.0.7 on 2026-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_programme_conditions_session_date_limite_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='formations.lecon'),
        ),
    ]
